/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a27e75d7-6dee-43b2-9d5a-485f3e6d1977",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4VjbPQkiJ",
    "aws_user_pools_web_client_id": "5i9f5fhtsmuaujkg54gflc0qgo",
    "oauth": {}
};


export default awsmobile;
